# Minimal Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: "@batpb/genart - generative art library"
description: A TypeScript compatible library built on p5.js for creating responsive generative art projects.
logo: "https://brittni-and-the-polar-bear.github.io/assets/img/logo.png"
show_downloads: true

include:
  - "**/variables/_*.html"
  - "**/variables/*.html"
  - "**/variables/*"
  - "./doc/variables/"
  - "/doc/variables/"
  - "doc/variables/"
  - "**/variables/_*_.html"
  - "./doc/variables/_*.html"
  - "./doc/variables/*.html"
  - "./doc/variables/*"
  - "./doc/variables/_*_.html"
  - "/doc/variables/_*.html"
  - "/doc/variables/*.html"
  - "/doc/variables/*"
  - "/doc/variables/_*_.html"
  - "_*_.html"
  - "*.html"
  - "**.html"
  - "_*.html"
  - "doc/**/*.html"
