# Minima theme configuration
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

# valid social icon names can be found at https://fontawesome.com/search?ic=brands

minima:
  skin: auto
  hide_site_feed_link: true
  show_excerpts: false
  social_links:
  nav_pages:
    - index.md
    - colors/colors.md
    - palettes/palettes.md

title: "@batpb/genart - algorithmic generative art library"
description: "A TypeScript compatible library built on p5.js for creating responsive, generative, algorithmic art projects."
show_downloads: true

collections_dir: "./_collections"

collections:
  palette_colors:
    output: true
    sort_by: luminance
  palettes:
    output: true
    sort_by: name

include:
  - "_*.html"

exclude:
  - Gemfile
  - Gemfile.lock
  - .bundle
