# Minima theme configuration
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

# valid social icon names can be found at https://fontawesome.com/search?ic=brands

minima:
  skin: auto
  hide_site_feed_link: true
  show_excerpts: false
  social_links:
    - title: "GitHub Pages"
      icon: github-alt
      url: "https://brittni-and-the-polar-bear.github.io/"
    - title: "GitHub"
      icon: github
      url: "https://github.com/brittni-and-the-polar-bear"
  nav_pages:
    - index.md
    - getting-started.md

title: "@batpb/genart - generative art library"
description: "A TypeScript compatible library built on p5.js for creating responsive, generative, algorithmic art projects."
logo: "https://brittni-and-the-polar-bear.github.io/assets/img/logo.png"
show_downloads: true

collections_dir: "./collections"

collections:
  palette_colors:
    output: true
    sort_by: luminance

include:
  - "_*.html"

exclude:
  - Gemfile
