# Minimal Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: @batpb/genart - generative art library
description: A TypeScript compatible library built on p5.js for creating responsive generative art projects. Built by brittni and the polar bear.
logo: "https://brittni-and-the-polar-bear.github.io/assets/img/logo.png"
show_downloads: true
