# Minimal Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: generative art library | brittni and the polar bear
description: a TypeScript compatible library built on p5.js for creating responsive generative art projects.
logo: "https://brittni-and-the-polar-bear.github.io/assets/img/logo.png"
show_downloads: true
